apiVersion: v1
kind: Service
metadata:
  name: cinema-bot
spec:
  selector:
    app: cinema-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30020
  type: ClusterIP
