spring:
  application.name: backend
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:158.160.157.207}:${DATABASE_PORT:5432}/${DATABASE_NAME:cinemadb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml

server:
  port: 8080

management:
  server.port: 8081
  endpoint:
    health.access: read_only
    info.access: read_only
    metrics.access: unrestricted
    prometheus.access: unrestricted
    loggers.access: read_only
  endpoints.web.exposure.include: health,info,prometheus,metrics,loggers

pushgateway.url: http://158.160.157.207:9091/metrics/job/backend-metrics-collection-job/service/cinema-backend/instance/${POD_NAME:cinema-backend}
bot.url: http://158.160.157.207:30020/event
