INSERT INTO movies(title, year, genre, director, movie_cast, rating, description, poster_url)
VALUES ('Inception',
        2010,
        'Sci-Fi, Action',
        'Christopher Nolan',
        'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy',
        8.8,
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
       ('The Shawshank Redemption',
        1994,
        'Drama',
        'Frank Darabont',
        'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler',
        9.3,
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg'),
       ('The Dark Knight',
        2008,
        'Action, Crime, Drama',
        'Christopher Nolan',
        'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
        9.0,
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
       ('Pulp Fiction',
        1994,
        'Crime, Drama',
        'Quentin Tarantino',
        'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis',
        8.9,
        'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
       ('The Lord of the Rings: The Return of the King',
        2003,
        'Adventure, Drama, Fantasy',
        'Peter Jackson',
        'Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom',
        8.9,
        'Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
        'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg');

INSERT INTO reviews(username, rating, comment, review_date, movie_id)
VALUES ('moviefan123', 9, 'Mind-blowing concept and execution!', '2025-04-15', 1),
       ('cinephile', 8, 'Visually stunning but the plot gets convoluted.', '2025-03-22', 1),
       ('filmcritic', 10, 'Absolute masterpiece of storytelling.', '2025-04-10', 2),
       ('dcfan', 10, 'Heath Ledgers Joker is iconic!', '2025-03-18', 3),
       ('batmanfan', 9, 'Best superhero movie ever made.', '2025-02-05', 3),
       ('tarantinofan', 9, 'Brilliant non-linear storytelling.', '2025-03-12', 4),
       ('tolkienfan', 10, 'Perfect conclusion to an epic trilogy.', '2025-02-28', 5);